title: Devar-TTY
description: Founder of Team Expiration, Freelance Writer, Content Creator, and Professional Game Master
show_downloads: true
google_analytics:
theme: jekyll-theme-dinky

links:
    twitch: https://twitch.tv/devartty
    facebook: https://facebook.com/officialdevartty
    instagram: https://instagram.com/devartty
    twitter: https://twitter.com/devartty
    discord: https://discord.gg/PRjtw9B

yawamtsurl: "/assets/images/yawamt/"
